nodeLinker: node-modules
# @template-customization-start
yarnPath: .yarn/releases/yarn-4.0.2.cjs # Needed to prevent race conditions in CI: https://github.com/actions/setup-node/issues/899
# @template-customization-end
